### ISSUE TITLE
IPNS tutorial (and tutorials on other new features)

### ISSUE THREAD

**Issue by DonaldTsang** [Siderus/Orion#129]
Create a guide (or at least a GIF image) of using IPNS.

**Comment by koalalorenzo** [comment]
Hi! There is already a GIF to use IPNS, but we still have to populate https://orion.siderus.io 

What would be the use case that you want to showcase? Add a file to IPNS and retrieve it?

At the moment IPNS is very slow due to the current `go-ipfs` implementation, so we are kinda waiting to get it better before showcasing this feature, even if it is already implemented :)

**Comment by roscoevanderboom** [comment]
I did some test using Siderus Orion, Go-ipfs and IPFS Manager. Creating three nodes and then using Orion to manage the other nodes. 1 success and 1 fail. 

https://siderus.io/ipfs/Qme9BJnKYHuUMahDFnwxf4reZM31KA9fDneV2KHo84Zup3

**Comment by roscoevanderboom** [comment]
I'm putting together a video series about how to use Orion, Go-ipfs and IPfS-manager. Hope it will get more people to help build.

https://www.youtube.com/channel/UCPixw90-zJJRztMfsXdHBug

**Comment by koalalorenzo** [comment]
@roscoevanderboom we have a channel on Matrix ( 
https://riot.im/app/#/room/%23orion:matrix.org ) where we are trying to push people to go if they have quick question or something related. It would be nice if you could also talk about it during the videos :P 

Anyway, I saw that you have a lot of videos that are very helpful! it would be nice if we could check what we can cover and help you covering it! for example: there are features that can help you to do the same thing you did with the CLI in the other videos. We can help you discover more as well as implement new based on the use cases.

The next features we are implementing is "Send To" and "Sharing feature" so that you can share files with friends. In the next month we should have ready also a feature that will allow you to connect to friends by just sharing the multiaddress / PeerID so that in some restricted network (ex: Intranet or custom VPN) it is possible to share files directly between nodes.

**Comment by roscoevanderboom** [comment]
Hi Lorenzo,

Thanks for keeping me informed. It's awesome being part of the movement. There are already so many videos talking about what IPFS is and it's implications/implimentations. These videos make non-initiates, like most of my friends, confused. Also most people can't see how it's better, simpler and more convenient than http unless they are developers and enthusiasts. The matrix chat group is even way above my experience level.

My videos will focus on more simple use cases. Especially focusing on how to setup a windows desktop with shortcuts and browser setup to do all the things centralized services offer, but through ipfs and keeping the control in the user's hands without making them feel overwhelmed.

The new features are exactly what I was hoping for! Personal VPN and sharing. I will definitely keep adding more videos as you add features.

Some things I could imagine for the future:

Windows explorer integration

- right-click--->add to IPFS (which would also print out the hash ready to copy/paste into social media clients)
- right-click--->add to IPNS (add+publish)
- right-click--->add and send to known friends(peerID)...this way will eliminate the need for social media clients

Orion features (I imagine Orion managing more than 1 peerID/PC)

- create new peerID
- choose which peerID to publish to (i already have 3 peerIDs. It would be awesome if Orion becomes an IPNS client to manage them all.)

Encryption is not such a big worry for me. I use winRAR or VeraCrypt. These are pretty easy for common encryption...not military :P

Thanks again for the great app. I'll keep testing. I have noticed some performance issues in the new release. Sometimes adding content makes client non-responsive but it finally gets there. All-in-all it works very well

Regards,
Roscoe

PS....the project should have been called "IPNS".....most people get so lost when they hear IPFS all the time, but finally I tell them that their IPNS address is the most important.

**Comment by koalalorenzo** [comment]
@roscoevanderboom I noticed in one on the video that you are not using drag and drop feature on Orion, while instead you are doing so with IPFS Manager. Would you explain to me why or if you knew that Orion has this feature?

I am investigating around why we sometimes fail in making these interactions intuitive, or explained enough for users to use them.

**Comment by roscoevanderboom** [comment]
Sorry if I didn't mention drag and drop. As you can see I'm really new at this. I will continue to add videos showing everyday use. I will use drag and drop in future videos. If more people are interested, I will do more thorough reviews of the clients. But is my technical knowledge is limited, I try to stick to things I know.

Next I will make a video showing the same basic add, publish, share actions in Orion, IPFS-Manager and go-ipfs cli.

Soon I will start to focus more on simple html designs to make nodes look cool and interesting to visit. Not just a folder view.

I favorite features....Orion keeps a history, easy to view peer info.

IPFS manager seems a little faster adding and publishing. Also after publishing there isn't helpful print out of different ways to link to hash, ie gateway+hash and QR code hash.

I think that would be easy to incorporate into Orion. My dream feature now is add+publish to peerID. Maybe you can create 2 areas in the interface. where a user can drag and drop. 1 area is add , other area is for publish. Something like drop into a chest to add / drop onto a profile pic to publish.

Later when you add private connection there can be a list of peers. User drags and drops on the icon, picture of friend to send private link.

I'm looking forward to next updates!!

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by koalalorenzo** [comment]
Can we close this issue?
If I don't get any answer I will close it in few days :)
