### ISSUE TITLE
Preferences: point Orion to a pre-existing local ipfs node to use instead of the built-in node

### ISSUE THREAD

**Issue by JayBrown** [Siderus/Orion#162]
**Is your feature request related to a problem? Please describe.**
Orion uses a built-in ipfs node, and it would be nice to use the node already in use on a system.

**Describe the solution you'd like**
In Preferences let the user choose a pre-existing local node, e.g. in `$HOME/.ipfs` to use instead of Orion's built-in node, with support for MFS (File API)

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by koalalorenzo** [comment]
You can already use an existing node. What you have to do is to run the ipfs daemon in the background before starting Orion (`go-ipfs` for now).

The reason why we are not using the pre-existing one is that we change the configuration as well as we may implement custom setup to the way we store data. (Multiple versions of IPFS may not be compatible)... jumping between versions may break the ipfs repo. For the current state this is something that it is very hard to support! 

Do you have any suggestion to how we could change this for future releases? For now we just allow users to run another daemon in background and use it instead of the included one.

**Comment by roscoevanderboom** [comment]
First, big thanks!! This is a great application. 

The version compatibility issues will become less as more people start adopting a certain implementation of IPFS. I think its gonna be like an avalanche. Then everyone else has to join the same network and some will keep using smaller networks. The race is on!! 

I do have many ideas but will start with something simple. Would it be possible to have a "Create new node" function? The purpose is for my website. I use IPNS to host my site but I can only publish  1 IPFS hash (main site directory) at a time.  If I could init more nodes, I could link those IPNS names in my main namespace (webpage).

This way I would have IPNS links within my namespace.  I currently do this by running go-ipfs and Siderus Orion separately and duplicating the process in Ubuntu VirtualBox to get 4 nodes. 

This is not a big workaround but it would be a lot easier if all this functionality built straight into Orion Client.

**Comment by koalalorenzo** [comment]
Closing this issue as it is mostly related to IPFS itself (and different versions of the repository)
