### ISSUE TITLE
Snap package

### ISSUE THREAD

**Issue by NatoBoram** [Siderus/Orion#189]
**Is your feature request related to a problem? Please describe.**

Orion is currently impossible to install via a package manager for non-debian distributions.

**Describe the solution you'd like**

The Snap Store solves this problem. By publishing a Snap package of Orion, any Linux distribution would be able to install Orion and many more problems are solved at the same time.

**Describe alternatives you've considered**

There's always Flatpack, but it's nowhere as convenient as Snaps, and I'd rather use APT than Flatpack.

**Additional context**

**Comment by koalalorenzo** [comment]
That sounds like a good idea! 
For now we are providing packages for redhat-based (rpm), debian-based (deb), archlinux and alpinelinux. You can download the package you need from the release, but of course if it does not include your distro (ex: if it is a linux from scratch) we need to make snap package!

I will add a task for this. The ETA could be 2-3 weeks if everything goes correctly. Otherwise it will be in a month.

**Comment by NatoBoram** [comment]
*Amazing!*

I saw that Orion was an Electron app, I think those instructions can help!

https://docs.snapcraft.io/build-snaps/electron
