### ISSUE TITLE
Progress bar

### ISSUE THREAD

**Issue by roscoevanderboom** [Siderus/Orion#207]
OS: Linux 
Orion version: 1.0

Some kind of status bar to show uploads in progress. I also miss the popup showing details after a file was uploaded.

**Comment by koalalorenzo** [comment]
The progress bar is in the Activities panel,
We might integrate it with the global loading bar in the app and probably move the activities panel into its own button on the main app bar (the one at the top).

About the popup, we switched to not show the popup due to the fact that there is a case where the user may add more than one file at the time. This might break the flow.

If we highlight the new content/file added, will that help?
(ex: When you add a file and it is completed, In the Storage List for 30 seconds it will be with a different color). 

Is that helping?

**Comment by roscoevanderboom** [comment]
Highlight new items will be perfect.

**Comment by roscoevanderboom** [comment]
I closed this as I feel the current notifications are working well.
