### ISSUE TITLE
Open IPNS 

### ISSUE THREAD

**Issue by roscoevanderboom** [Siderus/Orion#208]
Creating multiple peerIDs is great! Thanks. Please add "Open in browser" to the "actions" button options.

**Comment by koalalorenzo** [comment]
Great idea! We will implement that before the final release.

I will ping you when the beta release will be updated (there should be no need to re-download the app, it will automatically update the interface)

**Comment by koalalorenzo** [comment]
@roscoevanderboom This has been fixed in the latest beta of v1.0

Please, run the application and test it. It will automatically use the latest version of the interface with the latest updates :) _We added also "Copy Hash" button!_

Let me know if this issue is fixed for you, in case I will close the issue in few days!
