### ISSUE TITLE
Ability to add files/folders to an existing one

### ISSUE THREAD

**Issue by tiotrom** [Siderus/Orion#225]
Since one can create an IPNS link then would be great to be able to add/move files/subfolders inside a folder. The original ipfs-desktop application allows for that. Cheers!

**Comment by koalalorenzo** [comment]
Orion manages Pins, while the desktop app you are referring to is managing a mutalbe file system, which allows you to move files/directories and modify things. This causes the IPFS hash to change and it is a wrong user experience considering the premises of IPFS.

Think about sharing the CID with somebody and then modifying the content, the CID shared is no longer valid.

Opting to IPNS is not even a stable solution as it requires your node to be available in order to have better chances to have it working.

I am closing this, but it is a valid point! Until Protocol Labs fixes their user experience issues we can't work on this issue. Sorry
