### ISSUE TITLE
Cannot move window when Dev Tools are showing.

### ISSUE THREAD

**Issue by NeoTeo** [Siderus/Orion#88]
You can move the window using only the "trick" of selecting the deselected window and moving it in the same action.

**Comment by koalalorenzo** [comment]
Fixed in #82 :)

**Comment by koalalorenzo** [comment]
Sorry I Mixed the issues.
This is probably due to the fact that with the StorageList window (the main one) we hide the system bars for dragging the window. If you open the Dev Window as an detached windows, it will do the trick.

I will close this as it is not probably affecting all the end users but only the developers :) Please re open if it gets a real issue causing other problems!
